#!/usr/bin/env bash
# A bash script that prints information about subdomains.

function get_sub_info {
  local domain=$1
  local subdomain=$2
  local full_domain="${subdomain}.${domain}"
  
  # Capture the IP address using dig
  local record_ip=$(dig +short ${full_domain})

  # If no IP found, return a message
  if [[ -z "$record_ip" ]]; then
    echo "No IP address found for ${full_domain}"
    return
  fi

  # Print the information about the A record
  echo "The subdomain ${subdomain} is a A record and points to ${record_ip}"
}

domain=$1
subdomain=$2

if [[ -z "$subdomain" ]]; then
  # If no subdomain is specified, check default subdomains
  for sub in www lb-01 web-01 web-02; do
    get_sub_info $domain $sub
  done
else
  # If a subdomain is specified, check only that subdomain
  get_sub_info $domain $subdomain
fi
